### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by shchedrin** [rarus/rarus-kkt-php-sdk#13]
Trying to install package at Laravel 9, facing monolog version error
Your package requires `"monolog/monolog": "1.*",`, but Laravel nend at least `"monolog/monolog": "^2.0",`
May be you can update?

**Comment by Absurdd** [comment]
@shchedrin fixed in https://github.com/rarus/rarus-kkt-php-sdk/releases/tag/2.1.3, monolog updated to actual "monolog/monolog": "3.*"
